
[target.x86_64-pc-windows-msvc]
rustflags = [ "-C", "link-args=/EXPORT:AmdPowerXpressRequestHighPerformance /EXPORT:NvOptimusEnablement"]

[target.i686-pc-windows-msvc]
rustflags = [ "-C", "link-args=/EXPORT:AmdPowerXpressRequestHighPerformance /EXPORT:NvOptimusEnablement"]
